version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "development"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 99
