name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: xt0rted/stylelint-problem-matcher@v1.3.0

      - uses: actions/checkout@v4.1.2

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: current

      - run: npm ci --omit=dev

      - run: npm install
        working-directory: test

      - run: npm run test:string
        working-directory: test
