name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.3

      - name: Install node
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 14

      - run: npm ci

      - run: npm test
