name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install node
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 14

      - run: npm ci

      - run: npm test
