name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3.0.1

      - name: Install node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm test
